{% set name = "Brian2" %}
{% set version = "2.6.0" %}
{% set sha256 = "a98788327f25d95d829298f9018ed35a28459df67ffc970fe5569c5147d809fe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [python_impl == 'pypy' or py < 39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >= 1.21                          # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - setuptools >=61
    - setuptools_scm >=6.2
    - numpy >= 1.21
  run:
    - python
    # we don't need the same version as during the build, newer versions are
    # still ABI-compatible
    - {{ pin_compatible('numpy') }}
    - sympy >=1.2
    - pyparsing
    - scipy >=0.13.3
    - gsl >1.15
    - cython >=0.29.21
    - jinja2 >=2.7
    - setuptools >=61
    - packaging
    - py-cpuinfo  # [win]
    - {{ compiler('cxx') }}  # [unix]

test:
  imports:
    - brian2
    - brian2.codegen
    - brian2.codegen.generators
    - brian2.codegen.runtime
    - brian2.codegen.runtime.cython_rt
    - brian2.codegen.runtime.numpy_rt
    - brian2.core
    - brian2.devices
    - brian2.devices.cpp_standalone
    - brian2.equations
    - brian2.groups
    - brian2.input
    - brian2.memory
    - brian2.monitors
    - brian2.parsing
    - brian2.spatialneuron
    - brian2.sphinxext
    - brian2.stateupdaters
    - brian2.synapses
    - brian2.tests
    - brian2.tests.features
    - brian2.units
    - brian2.utils

  requires:
    - pytest

about:
  home: http://www.briansimulator.org/
  dev_url: https://github.com/brian-team/brian2
  doc_url: http://brian2.readthedocs.io/
  license: CECILL-2.1
  license_file: LICENSE
  summary: A clock-driven simulator for spiking neural networks
  description: |
    Brian2 is a simulator for spiking neural networks available on almost all platforms.
    The motivation for this project is that a simulator should not only save the time of
    processors, but also the time of scientists.

    It is the successor of Brian1 and shares its approach of being highly flexible
    and easily extensible. It is based on a code generation framework that allows
    to execute simulations using other programming languages and/or on different
    devices.

extra:
  recipe-maintainers:
    - mstimberg
    - thesamovar
