appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: G99XrrYe1IOV8DYxQjBFZ0V/Id1wuJzu4pgcORzQv2swaBC7ccv1zLfhLtnzKpx8/oGK+C4RJzHhT+AH2J2hj0GItQLgzBdWCzTAAmvOwu84r2xmMtCbG8AJ1DGtGM9LOXecnANWeS6dHJBX9nAENi4sN6xGFsF055FcPTLEKjl8k6aaBnuBnYVwlcJZd+fjJe4hsnxy6HifYHLkRe8ZOh+/OOl0drdPJPMnlV9kSEBXUl1wv3KyCZK8bp3vgM+Ui3A/+YoCz1OL1LgXE5z1a1odz40YsCkhuYEP5bffGJOVp1xd1fMZupbfUuilcPW/DCbkYwMJUnw6NN8j/oGeGrFj0JjF+M6LMkZDyDytRpD50QBeOxEdm99p5867M0xqZRNCL36SzYd4fe8UfQLwORXq+T+QCe/iDbjtPYXvrUYUUDvb7co/uBaA3+WOF7Q1hdzDcWyoren23k55/PgUVu3oooPiE97HBc8GSsC6FQbBA6ggWT0TwOys14/IyfR2wAlVqmtNZxaX96lYushI2Ho0ZVZ1dS2cPqTmjre6ASbsbk1/Z/+vaqRQE6mGUBVires6eTyJDXAiTUWMW5PHZbmEG3iU8EdUX+UgWp1slju7durL2uOMMKI1JzqCYgLwsG4e9CfwHRKtO7Ic60TBmhLQrMQTgtoe1+7J2l2iADE=}
